### ISSUE TITLE
Checklist for migration guide

### ISSUE THREAD

**Issue by bzm3r** [StarArawn/bevy_ecs_tilemap#275]
- [ ] `(0, 0)` will be at at the center of the tile for all tile types
- [ ] helper names have changed, in particular, `get_centered_transform_2d` is now `get_tilemap_center_transform`
- [ ] actually use migration guide checklist when making a new version 🤦
